# Generated by Django 5.1 on 2024-08-23 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiversionSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['gender'],
            },
        ),
        migrations.CreateModel(
            name='IntakeReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Statuses',
                'ordering': ['status'],
            },
        ),
        migrations.CreateModel(
            name='TurnawayOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TurnawayReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_consent', models.BooleanField(default=False)),
                ('unique_id', models.CharField(blank=True, help_text='Do not assign or alter Unique IDs.', max_length=6, null=True, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(help_text='Include any variations, including spelling, when unconfirmed.', max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('otherinfo', models.CharField(blank=True, max_length=500, null=True)),
                ('guest_ID', models.CharField(editable=False, max_length=6, unique=True)),
                ('first_intake', models.DateField(blank=True, help_text='Date of first intake.', null=True)),
                ('intake_period', models.CharField(blank=True, help_text='Reporting period at first access.', max_length=20, null=True)),
                ('most_recent_intake', models.DateField(blank=True, help_text='Most recent month and year of intake.', null=True)),
                ('status_notes', models.TextField(blank=True, help_text='Additonal Information pertaining to Status or otherwise, include dates', max_length=1000, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('other_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='overnight.gender')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='overnight.status')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='HPP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hifis_id', models.CharField(help_text='Do not assign or alter HIFIS IDs.', max_length=100)),
                ('housing_status', models.CharField(blank=True, choices=[('Experiencing Homelessness', 'Experiencing Homelessness'), ('At Risk', 'At Risk')], help_text='Housing status at program entry.', max_length=100, null=True)),
                ('chronic_homeless', models.BooleanField(default=False, help_text='Chronically homeless 6+ months.')),
                ('indigenous', models.BooleanField(default=False, help_text='Identifies as indigenous.')),
                ('from_institution', models.BooleanField(default=False, help_text='Transitioned from provincial institution immediately prior to entering the program.')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overnight.guest')),
            ],
            options={
                'verbose_name_plural': 'HPPs',
                'ordering': ['guest'],
            },
        ),
        migrations.CreateModel(
            name='Intake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('other_info', models.TextField(blank=True, max_length=500, null=True)),
                ('notes', models.TextField(blank=True, max_length=1000, null=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overnight.guest')),
                ('reason', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='overnight.intakereason')),
            ],
        ),
        migrations.CreateModel(
            name='Turnaway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('follow_up', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, max_length=1000, null=True)),
                ('diversion_support', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='overnight.diversionsupport')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overnight.guest')),
                ('outcome', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='overnight.turnawayoutcome')),
                ('reason', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='overnight.turnawayreason')),
            ],
        ),
    ]
