# Generated by Django 5.1 on 2024-08-23 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overnight', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='guest_ID',
        ),
    ]
