# Generated by Django 5.1.1 on 2024-09-10 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overnight', '0002_remove_guest_guest_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turnawayoutcome',
            options={'ordering': ['outcome']},
        ),
    ]
